apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: my-app
      image: nginx
      volumeMounts: 
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
