apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  clusterIP: None       # Headless service
  selector:
    app: web-app
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
