---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    env: dev
  namespace: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - name: http
          containerPort: 80

    - name: tomcat-container
      image: tomcat
      ports:
        - name: java
          containerPort: 8080

