apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    env: dev
  namespace: dev
spec:
  type: ClusterIP
  selector: 
    app: myapp
  ports: 
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: java
      port: 8080
      targetPort: 8080
      protocol: TCP